### ISSUE TITLE
Bulk

### ISSUE THREAD

**Issue by opheus2** [WeedmasterOG/Bombify-Email-Bomber#1]
How do i send bulk.?

**Comment by WeedmasterOG** [comment]
Bulk?, u mean send an amount?, i didnt build that in as its a bomber, made for one to send as much spam as possible, but u can do it manually by letting it run for a bit i guess

**Comment by WeedmasterOG** [comment]
if u wana talk about the bomber please add me on skype: live:kevinab1234
